site_name: My site
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: cyan
  font:
    text: Roboto
    code: Roboto mono

plugins:
  - blog
  
